// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACW1Adan_Nfqy9bYM8R1h1x-howqrgy4o',
    appId: '1:652682074206:web:328c07a93282988ba93ccf',
    messagingSenderId: '652682074206',
    projectId: 'marinetradeconnect-38ef6',
    authDomain: 'marinetradeconnect-38ef6.firebaseapp.com',
    storageBucket: 'marinetradeconnect-38ef6.firebasestorage.app',
    measurementId: 'G-7DX4V95KRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEpNRmFwfR_7pcnvGZn5ar_XXRVRGelnc',
    appId: '1:652682074206:android:fa9c5af074423c4ea93ccf',
    messagingSenderId: '652682074206',
    projectId: 'marinetradeconnect-38ef6',
    storageBucket: 'marinetradeconnect-38ef6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-S4sHhbL51tPfpqrQI6SuBF_wcSkBC0',
    appId: '1:652682074206:ios:99c92fbd0bdf94b3a93ccf',
    messagingSenderId: '652682074206',
    projectId: 'marinetradeconnect-38ef6',
    storageBucket: 'marinetradeconnect-38ef6.firebasestorage.app',
    iosBundleId: 'com.example.marineTradeConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS-S4sHhbL51tPfpqrQI6SuBF_wcSkBC0',
    appId: '1:652682074206:ios:99c92fbd0bdf94b3a93ccf',
    messagingSenderId: '652682074206',
    projectId: 'marinetradeconnect-38ef6',
    storageBucket: 'marinetradeconnect-38ef6.firebasestorage.app',
    iosBundleId: 'com.example.marineTradeConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACW1Adan_Nfqy9bYM8R1h1x-howqrgy4o',
    appId: '1:652682074206:web:c7ae67ee5643abb5a93ccf',
    messagingSenderId: '652682074206',
    projectId: 'marinetradeconnect-38ef6',
    authDomain: 'marinetradeconnect-38ef6.firebaseapp.com',
    storageBucket: 'marinetradeconnect-38ef6.firebasestorage.app',
    measurementId: 'G-G83PEKCSZZ',
  );
}
